形態素解析の前に半角空白を除去する
textlint-ja/textlint-rule-no-doubled-conjunction pull request #16
Opened 2021-12-28 02:27 UTC by HelloRusk

fix #14 

同様の事象に気づいたため PR を送りました。

2022-07-30 23:37 UTC, azu requested changes
すみません。通知が来てなくて見るのが遅れました。

2022-07-30 23:37 UTC, azu commented on src/no-doubled-conjunction.js
> +                    const whitespaceRemovedSentence = sentence.raw.replace(" ", "")
replaceしてしまうと、tokensの位置がずれてしまう気がします。

> 朝起きた。そ して昼は仕事をした。そ して夜に寝た

このようなケースでtokenの位置がずれて報告されるんじゃないかなと思います。(これは結構無理やりなケースですが…)
接頭辞なので、致命的なズレにはならない可能性はあります。

2022-07-30 23:37 UTC, azu commented on src/no-doubled-conjunction.js
> +                    const whitespaceRemovedSentence = sentence.raw.replace(" ", "")
replaceして元のテキストを変更するのではなく、
tokenizeしてから、tokensが接続詞 かつ spaceをconjunctionTokensとして扱わない方が適切な可能性がありそうです。

2022-07-31 00:36 UTC, kaisugi commented on src/no-doubled-conjunction.js
> +                    const whitespaceRemovedSentence = sentence.raw.replace(" ", "")
すみません、昔に出したPRなので自分でもどこが問題か忘れかけており... 😭 
これcloseしてazuさんに対応一任していただいても大丈夫です。

2022-07-31 13:27 UTC, closed without merging